Repository SDPepe/AppArt, pull requests merged in 2021-05, with the labels that each got.

#169 Users can upload profile images to Firebase Storage & Activity communication layout refactor
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sdp/appart/AdCreationUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/AdCreationVMTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/AdUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/CameraUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/DatabaseTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/LoginTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/PanoramaUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/PictureImportUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/ScrollingUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/SimpleUserProfileActivityTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/UserProfileActivityTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/UserVMTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/utils/serializers/UserSerializerTest.java
  app/src/main/java/ch/epfl/sdp/appart/AdActivity.java
  app/src/main/java/ch/epfl/sdp/appart/AdCreationActivity.java
  app/src/main/java/ch/epfl/sdp/appart/CameraActivity.java
  app/src/main/java/ch/epfl/sdp/appart/CreateUserActivity.java
  app/src/main/java/ch/epfl/sdp/appart/LoginActivity.java
  app/src/main/java/ch/epfl/sdp/appart/MainActivity.java
  app/src/main/java/ch/epfl/sdp/appart/PicturesImportActivity.java
  app/src/main/java/ch/epfl/sdp/appart/ScrollingActivity.java
  app/src/main/java/ch/epfl/sdp/appart/SimpleUserProfileActivity.java
  app/src/main/java/ch/epfl/sdp/appart/UserProfileActivity.java
  app/src/main/java/ch/epfl/sdp/appart/ad/Ad.java
  app/src/main/java/ch/epfl/sdp/appart/ad/AdCreationViewModel.java
  app/src/main/java/ch/epfl/sdp/appart/ad/AdViewModel.java
  app/src/main/java/ch/epfl/sdp/appart/database/DatabaseService.java
  app/src/main/java/ch/epfl/sdp/appart/database/FirestoreDatabaseService.java
  app/src/main/java/ch/epfl/sdp/appart/database/FirestoreEmulatorDatabaseServiceWrapper.java
  app/src/main/java/ch/epfl/sdp/appart/database/MockDatabaseService.java
  app/src/main/java/ch/epfl/sdp/appart/database/firebaselayout/AdLayout.java
  app/src/main/java/ch/epfl/sdp/appart/database/firebaselayout/FirebaseLayout.java
  app/src/main/java/ch/epfl/sdp/appart/database/firestoreservicehelpers/FirestoreAdHelper.java
  app/src/main/java/ch/epfl/sdp/appart/database/firestoreservicehelpers/FirestoreImageHelper.java
  app/src/main/java/ch/epfl/sdp/appart/database/firestoreservicehelpers/FirestoreUserHelper.java
  app/src/main/java/ch/epfl/sdp/appart/scrolling/card/CardAdapter.java
  app/src/main/java/ch/epfl/sdp/appart/user/AppUser.java
  app/src/main/java/ch/epfl/sdp/appart/user/User.java
  app/src/main/java/ch/epfl/sdp/appart/user/UserViewModel.java
  app/src/main/java/ch/epfl/sdp/appart/utils/ActivityCommunicationLayout.java
  app/src/main/java/ch/epfl/sdp/appart/utils/serializers/UserSerializer.java
  app/src/main/res/drawable/user_example_female.png
  app/src/main/res/drawable/user_example_male.png
  app/src/main/res/drawable/user_example_no_gender.png
  app/src/main/res/layout/activity_simple_user_profile.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/ch/epfl/sdp/appart/ActivityCommunicationLayoutTest.java
  app/src/test/java/ch/epfl/sdp/appart/AdUnitTest.java
  app/src/test/java/ch/epfl/sdp/appart/AppUserTest.java
  app/src/test/java/ch/epfl/sdp/appart/CardUnitTest.java
  app/src/test/java/ch/epfl/sdp/appart/MockDatabaseTest.java
  app/src/test/java/ch/epfl/sdp/appart/UserViewModelTest.java
Labels: enhancement

#199 Fix app crash on camera activity for API less than 29
  app/src/main/java/ch/epfl/sdp/appart/CameraActivity.java
  app/src/main/java/ch/epfl/sdp/appart/utils/PermissionRequest.java
Labels: fix

#177 Design Refactor
  app/src/androidTest/java/ch/epfl/sdp/appart/AdCreationUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/AdUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/ApplicationConfigurationTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/DatabaseTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/FavoriteUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/FullScreenImageUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/LoginTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/PanoramaUIImageLoadFailedTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/PanoramaUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/PictureImportUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/ScrollingUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/SimpleUserProfileActivityTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/UserProfileActivityTest.java
  app/src/main/java/ch/epfl/sdp/appart/AdActivity.java
  app/src/main/java/ch/epfl/sdp/appart/AdCreationActivity.java
  app/src/main/java/ch/epfl/sdp/appart/CameraActivity.java
  app/src/main/java/ch/epfl/sdp/appart/LoginActivity.java
  app/src/main/java/ch/epfl/sdp/appart/UserProfileActivity.java
  app/src/main/res/drawable/button_primarly.xml
  app/src/main/res/drawable/card_shape.xml
  app/src/main/res/drawable/edit_text_default.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_add_image.xml
  app/src/main/res/drawable/ic_add_photo.xml
  app/src/main/res/drawable/ic_arrow_backward.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_forward.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_contact.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit_user.xml
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_lock.xml
  app/src/main/res/drawable/ic_new_account.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_vrpano.xml
  app/src/main/res/drawable/style_primary.xml
  app/src/main/res/drawable/style_rolling.xml
  app/src/main/res/drawable/style_secondary.xml
  app/src/main/res/layout/activity_adcreation.xml
  app/src/main/res/layout/activity_announce.xml
  app/src/main/res/layout/activity_camera.xml
  app/src/main/res/layout/activity_create_user.xml
  app/src/main/res/layout/activity_favorite.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_pictures_import.xml
  app/src/main/res/layout/activity_reset.xml
  app/src/main/res/layout/activity_scrolling.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/card_layout.xml
  app/src/main/res/layout/panoramagl.xml
  app/src/main/res/layout/photo_layout.xml
  app/src/main/res/layout/picture_import_card_layout.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: design

#208 Step counter activity & sensor usage
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sdp/appart/StepCounterActivity.java
  app/src/main/java/ch/epfl/sdp/appart/ToolbarActivity.java
  app/src/main/java/ch/epfl/sdp/appart/utils/PermissionRequest.java
  app/src/main/res/drawable/ic_step_counter.xml
  app/src/main/res/layout/activity_step_counter.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/menu/actions_toolbar.xml
  app/src/main/res/menu/ad_toolbar.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#219 StepCounterActivity test and bug fix
  app/src/androidTest/java/ch/epfl/sdp/appart/AdCreationUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/StepCounterActivityTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/adui/AdFailedInitTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/adui/AdUITest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/favoritesui/FavoriteFailedInitTest.java
  app/src/androidTest/java/ch/epfl/sdp/appart/userui/UserProfileActivityTest.java
  app/src/main/java/ch/epfl/sdp/appart/CameraActivity.java
  app/src/main/java/ch/epfl/sdp/appart/MainActivity.java
  app/src/main/java/ch/epfl/sdp/appart/StepCounterActivity.java
  app/src/main/java/ch/epfl/sdp/appart/utils/ActivityCommunicationLayout.java
  app/src/main/res/drawable-anydpi/ic_close_counter.xml
  app/src/main/res/layout/activity_step_counter.xml
  app/src/main/res/values/strings.xml
Labels: coverage, fix

#218 Sprint 11 summaries
  summaries/sprint11.md
Labels: documentation
